CREATE DATABASE IF NOT EXISTS Sistema;
USE Sistema;

//USE ESSE TEMPLATE DE INIT PARA CRIAR AS TABELAS DO BANCO DE DADOS SÓ COPIE O INIT.SQL (EXEMPLO: init_pablo.sql) E COLOQUE SEU NOME,
//VAMOS SEPARAR CADA INIT PARA DEPOIS AGRUPAR TODAS AS TABELAS EM UM SÓ ARQUIVO, PARA NÃO FICAR MUITO GRANDE E CONFUSO,
//E PARA PODER SEPARAR OS MÓDULOS DO SISTEMA, COMO POR EXEMPLO: USUÁRIO, PRODUTO, PEDIDO, ETC.

CREATE TABLE IF NOT EXISTS User(
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	hash VARCHAR(200) NOT NULL,
	);